---

- name: Install package
  become: True
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - containerd
    - aufs-tools

- name: Create config directory
  become: True
  file:
    name: /etc/containerd
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Configure service
  become: True
  template:
    src: config.toml.j2
    dest: /etc/containerd/config.toml
    owner: root
    group: root
    mode: 0644
  notify: Restart service

- name: Start service
  become: True
  service:
    name: containerd
    state: started
    enabled: True

- name: Flush handlers
  meta: flush_handlers
