---

- name: Install package
  become: True
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - containerd.io
    - aufs-tools

- name: Configure service
  template:
    src: config.toml.j2
    dest: /etc/containerd/config.toml
    owner: root
    group: root
    mode: 0644
  notify: Restart service

- name: Start service
  service:
    name: containerd
    state: started
    enabled: True

